### PR TITLE
Greyed out checkbox tree variant

### PR DESCRIPTION
**Pull request by alexchan7432**
Added greyed out text if a child is not selected or if the parent has unselected children.
This accounts for the previous disabled states.  Only the text is greyed out.  Differentiates from disabled which shows both the checkbox and text as greyed out.

Screen Shot 2021-01-28 at 8 51 55 AM

### CODE REVIEW

**Review by ironprice91 — APPROVED** [review]
I tested it out locally and it looks good

**Comment by herrethan** [comment]
I don't understand the use case here. Is there some doc that describes it?

**Comment by alexchan7432** [comment]
> I don't understand the use case here. Is there some doc that describes it?

https://www.figma.com/file/9DxofuRF8kmOreVv8wmxe6/Configurable-Table-View?node-id=16%3A6
This is the styling for edit table column view.  I also confirmed with Cathy the Export Slideout should be similar.

**Comment by herrethan** [comment]
> https://www.figma.com/file/9DxofuRF8kmOreVv8wmxe6/Configurable-Table-View?node-id=16%3A6
> This is the styling for edit table column view. I also confirmed with Cathy the Export Slideout should be similar.

I still don't understand.  "if a child is not selected or if the parent has unselected children" — from who's perspective?
I think mixing disabled styling in with selected logic is a really bad idea.

**Comment by alexchan7432** [comment]
> > https://www.figma.com/file/9DxofuRF8kmOreVv8wmxe6/Configurable-Table-View?node-id=16%3A6
> > This is the styling for edit table column view. I also confirmed with Cathy the Export Slideout should be similar.
> 
> I still don't understand. "if a child is not selected or if the parent has unselected children" — from who's perspective?
> I think mixing disabled styling in with selected logic is a really bad idea.

Yea, I'm not a big fan of it either.  I asked Cathy again, and she agreed to change it to grey-900 in general and get rid of this disabled text.  We'll be changing it when we convert to liminal styling anyway.  I'll make the change.

**Comment by herrethan** [comment]
Cool, I talked to Joel about it too, i think they may be getting rid of the "inactive" state on these.

**Pull request closed without merging**
